version: '3'
services:
  superauman-mysql:
    image: 'mysql:latest'
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mydatabase
      - PMA_ARBITRARY=1
  phpmyadmin_service:
    image: 'phpmyadmin/phpmyadmin'
    depends_on:
      - 'superauman-mysql'
    # links:
    #   - 'superauman-mysql:db'
    ports:
      - '8080:80'
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
      - PMA_HOST=superauman-mysql
  superauman-server:
    build:
      context: ./server
    ports:
      - '5000:5000'